# Generated by Django 3.2.9 on 2022-08-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avionics_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessModel',
            new_name='process_file_repo',
        ),
    ]
