# Generated by Django 3.2.9 on 2022-08-10 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avionics_app', '0002_rename_processmodel_process_file_repo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='process_file_repo',
            table='process_file_repo',
        ),
    ]
