# Generated by Django 3.2.9 on 2022-08-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avionics_app', '0005_auto_20220810_1214'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='Project',
        ),
    ]
