# Generated by Django 3.2.9 on 2022-08-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avionics_app', '0006_alter_project_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_file_repo',
            name='project_name',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
