# Generated by Django 3.2.9 on 2022-08-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avionics_app', '0007_auto_20220810_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.AlterField(
            model_name='process_file_repo',
            name='project_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avionics_app.project'),
        ),
    ]
