# Generated by Django 3.2.9 on 2022-08-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avionics_app', '0008_auto_20220810_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_file_repo',
            name='process_name',
            field=models.CharField(max_length=26),
        ),
    ]
