# Generated by Django 3.2.9 on 2022-08-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avionics_app', '0009_alter_process_file_repo_process_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='process_file_repo',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
