# Generated by Django 3.2.9 on 2022-08-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avionics_app', '0010_auto_20220810_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='process_file_repo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=25)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('to_time', models.TimeField()),
                ('project_file', models.TextField()),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='avionics_app.project')),
            ],
            options={
                'db_table': 'process_file_repo',
            },
        ),
    ]
