# Generated by Django 3.2.9 on 2022-08-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avionics_app', '0013_process_file_repo_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_file_repo',
            name='project_name',
            field=models.CharField(default='00:00', max_length=25),
            preserve_default=False,
        ),
    ]
