# Generated by Django 3.2.9 on 2022-08-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avionics_app', '0014_alter_process_file_repo_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process_file_repo',
            name='process_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
