# Generated by Django 3.2.15 on 2022-09-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avionics_app', '0015_alter_process_file_repo_process_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='process_file_repo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
